name: Update flake.lock

on:
  schedule:
  - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Update flake.lock
      - uses: cachix/install-nix-action@v31      
      - run: nix flake update --flake ./src/config
      
      - name: Commit flake.lock changes
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Update Bot # defaults to "github-actions[bot]"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to "username <numeric_id+username@users.noreply.github.com>", where "numeric_id" and "username" belong to the author of the commit that triggered the run
          skip_dirty_check: false    
          create_branch: false
          skip_fetch: true
